### ISSUE TITLE
Build files outdated on latest release

### ISSUE THREAD

**Issue by acemir** [juliorosseti/vue-select-sides#16]
Hi @juliorosseti!

It seems that the build of the last release was not done.

I was trying to load the component from CDNs (like [jsDelivr ](https://cdn.jsdelivr.net/npm/vue-select-sides@1.1.4/dist/vueSelectSides.umd.min.js)or [UNPKG](https://unpkg.com/vue-select-sides@1.1.4/dist/vueSelectSides.umd.min.js)) and verified that they are still delivering the old version of the files.

**Comment by juliorosseti** [comment]
Sorry, my bad! Made available in version 1.1.5.

Tks for reporting!
