### ISSUE TITLE
Broken link in Readme (Live demo)

### ISSUE THREAD

**Issue by Roman-** [juliorosseti/vue-select-sides#46]
The "Live demo" on the project README leads to https://juliorosseti.github.io/vue-select-sides/demo.html?v=20201113113940 which gives 404 (There isn't a GitHub Pages site here.)

**Comment by gabrielcaixeta** [comment]
Thank you for reporting, @Roman- . It's back online now.

https://soft4ti.github.io/vue-select-sides/index.html?v=20201113113940
