### ISSUE TITLE
Please avail compiled css files

### ISSUE THREAD

**Issue by Mashiane** [juliorosseti/vue-select-sides#5]
Hi

Thanks for your components, can you please also avail css files?

Thanks

**Comment by juliorosseti** [comment]
Welcome @Mashiane!

Yep!

When I do, i'll tell you, ok?

**Comment by Mashiane** [comment]
I've managed to find this VSCode extension, not sure if it can do what you need.

https://marketplace.visualstudio.com/items?itemName=refgd.easy-compile

**Comment by Mashiane** [comment]
Actually the code on the demo folder works perfectly. Thing is it could be nice if all the example related css and js could be separated and just the needed stuff is left,

**Comment by juliorosseti** [comment]
> I've managed to find this VSCode extension, not sure if it can do what you need.
> 
> https://marketplace.visualstudio.com/items?itemName=refgd.easy-compile

Well... I need that when executing the build, the scss are compiled to css automatically through the vue-cli... Do you know how to do this?

**Comment by juliorosseti** [comment]
Good news Mr. @Mashiane,

Published version 1.0.5 on npm with new locale!
Available compiled css files:
* /node_modules/vue-select-sides/dist/css/soft.css - Default
* /node_modules/vue-select-sides/dist/css/dark.css
* /node_modules/vue-select-sides/dist/css/light.css

**Comment by juliorosseti** [comment]
Good news Mr. @Mashiane,

Published version `1.1.2` on npm with new css files!

Available files:
* /node_modules/vue-select-sides/dist/css/soft.css - Default
* /node_modules/vue-select-sides/dist/css/dark.css
* /node_modules/vue-select-sides/dist/css/light.css
