### ISSUE TITLE
Use any locale available in any app

### ISSUE THREAD

**Issue by juliorosseti** [juliorosseti/vue-select-sides#6]
Issue by @nioperas06

https://github.com/juliorosseti/vue-select-sides/pull/4#issuecomment-606037296

**Comment by nioperas06** [comment]
Hi, thinking about adding a locale props with default value: 'en_US'  🤔 
```
<vue-select-sides
  type="mirror"
  locale="fr_FR"
  v-model="selected"
  :list="list"
></vue-select-sides>
```

**Comment by juliorosseti** [comment]
> Hi, thinking about adding a locale props with default value: 'en_US' 🤔
> 
> ```
> <vue-select-sides
>   type="mirror"
>   locale="fr_FR"
>   v-model="selected"
>   :list="list"
> ></vue-select-sides>
> ```

The props `locale` not exists, use `lang`:

```
<vue-select-sides
  type="mirror"
  lang="fr_FR"
  v-model="selected"
  :list="list"
></vue-select-sides>
```

BTW, I'm working in global locale using `Vue.use(VueSelectSides, params)`

**Comment by juliorosseti** [comment]
Now, you can use globally locale @nioperas06 

```javascript
import vueSelectSides from "vue-select-sides";

Vue.use(VueSelectSides, {
  locale: "fr_FR"
});

Vue.component("vue-select-sides", VueSelectSides);
```

**Comment by khayyak** [comment]
@juliorosseti it's not working for me
